#!/usr/bin/env bash

readonly wize_flow_dir="$(git rev-parse --show-toplevel)"/.git/wize-flow
if [[ ! -d "$wize_flow_dir" ]]; then
    echo "Wize-flow was not installed correctly. Run 'wize-flow-setup.sh reinstall <repository-path> <git-hub-repository-url>'"
    exit 1
fi
"$wize_flow_dir"/pre-push-script || exit $?
