#!/usr/bin/env bash

protected_main_branch='master'
protected_dev_branch='develop'
push_command=$(ps -ocommand= -p $PPID)
if [[ ( "$push_command" == *" $protected_main_branch"* || "$push_command" == *" $protected_dev_branch"* ) && $AUTOMATED_PUSH != "true" ]]
then
  echo 'You cannot push directly to develop or master'
  exit 1
else
  exit 0
fi
