#!/usr/bin/env bash

# This script will prevent direct pushes to develop and master branches if FORCE_PUSH is different than true

protected_main_branch='master'
protected_dev_branch='develop'
push_command=$(ps -ocommand= -p $PPID)
current_branch=$(git rev-parse --abbrev-ref HEAD)

current_upstream_branch=$(git branch -vv | grep \* | grep "origin/$current_branch")
[[ ! -z "$current_upstream_branch" ]] && current_branch_upstreamed="true"

if [[ "$@" == *"origin"* && ( "$push_command" == *" $protected_main_branch"* || "$push_command" == *" $protected_dev_branch"* || ( ( "$current_branch" == "$protected_main_branch" || "$current_branch" == "$protected_dev_branch" ) && "$current_branch_upstreamed" == "true" ) ) && $FORCE_PUSH != "true" ]]; then
    echo 'You cannot push directly to develop or master on origin'
    exit 1
else
    exit 0
fi
